### ISSUE TITLE
/etc/openldap/schema/fusiondirectory/core*_update.ldif insertion failed!

### ISSUE THREAD

**Issue by xps2** [tiredofit/docker-openldap-fusiondirectory#6]
```
openldap-fusiondirectory-app    | SASL/EXTERNAL authentication started
openldap-fusiondirectory-app    | SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
openldap-fusiondirectory-app    | SASL SSF: 0
openldap-fusiondirectory-app    | executing 'ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/fusiondirectory/core*_update.ldif'
openldap-fusiondirectory-app    | SASL/EXTERNAL authentication started
openldap-fusiondirectory-app    | SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
openldap-fusiondirectory-app    | SASL SSF: 0
openldap-fusiondirectory-app    | ldapmodify: wrong attributeType at line 88, entry "cn={6}core-fd-conf,cn=schema,cn=config"
openldap-fusiondirectory-app    | Insertion failed!
```

**Comment by blasphemite** [comment]
I'm getting this same error on a new install and unable to contact LDAP server after container startup. Is there a known resolution?

```
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
executing 'ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/fusiondirectory/core*_update.ldif'
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
ldapmodify: wrong attributeType at line 98, entry "cn={6}core-fd-conf,cn=schema,cn=config"
Insertion failed!
```

docker-compose.yml
```
openldap:
    container_name: openldap
    hostname: ldap.example.lan
    ports:
        - 389:389
        #- 636:636
    volumes:
        - /etc/openldap/data:/var/lib/openldap
        - /etc/openldap/config:/etc/openldap/slapd.d
        - /etc/openldap/certs:/certs
        - /etc/openldap/backups:/data/backup
    environment:
        - ENABLE_ZABBIX=FALSE
        - ORGANIZATION=example
        - DOMAIN=example.lan
        - HOSTNAME=ldap.example.lan
        - ADMIN_PASS=***
        - CONFIG_PASS=***
        - ENABLE_READONLY_USER=TRUE
        - READONLY_USER_USER=readonly
        - READONLY_USER_PASS=***
        - ENABLE_BACKUP=FALSE
        - ENABLE_PPOLICY=FALSE
        - ENABLE_TLS=FALSE
        - REAPPLY_PLUGIN_SCHEMAS=TRUE
        - FUSIONDIRECTORY_ADMIN_USER=fd-admin
        - FUSIONDIRECTORY_ADMIN_PASS=***
    restart: on-failure
    image: tiredofit/openldap-fusiondirectory:1.4-7.1.2
```

I've tried deleting my mounted volumes and starting from scratch, but still results in the same error & being unable to contact LDAP server.
